language: android

android:
  components:
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

jdk:
  - oraclejdk8

before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod +x gradlew

script:
  - ./gradlew assemble