language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod +x gradlew
  - chmod +x environmentSetup.sh

script:
  - ./environmentSetup.sh
  - ./gradlew assemble